### ISSUE TITLE
Java params seems not to be handled properly

### ISSUE THREAD

**Issue by Vincent--** [jowy/puppet-druid#2]
I've started use your module few weeks ago and I have some issues...
It seems xmx parameter isn't handled correctly.

Are you sure you can put java parameter inside runtime.propertie file ?
I think of these lines :+1: 

    -server
    -Xmx<%= @jvm_heap_max %>
    -Duser.timezone=<%= @timezone %>
    -Dfile.encoding=<%= @encoding %>

I don't understand how supervisor could use these parameters ?

For example, I have these lignes in runtime.properties 

```
-server
-Xmx256m
-Duser.timezone=UTC
-Dfile.encoding=UTF-8
druid.host=
druid.port=8092
druid.zk.service.host=localhost
druid.announcer.type=legacy
druid.curator.compress=false
[...]
```

And the processes are like that : 

```
druid    16692 16686  0 14:45 ?        00:00:14 /usr/bin/java -classpath /var/lib/druid/current/*:/etc/druid/coordinator io.druid.cli.Main server coordinator
druid    16693 16686  0 14:45 ?        00:00:10 /usr/bin/java -classpath /var/lib/druid/current/*:/etc/druid/historical io.druid.cli.Main server historical
druid    16694 16686  0 14:45 ?        00:00:13 /usr/bin/java -classpath /var/lib/druid/current/*:/etc/druid/broker io.druid.cli.Main server broker
druid    16695 16686  0 14:45 ?        00:00:11 /usr/bin/java -classpath /var/lib/druid/current/*:/etc/druid/overlord io.druid.cli.Main server overlord
druid    16696 16686  0 14:45 ?        00:00:11 /usr/bin/java -classpath /var/lib/druid/current/*:/etc/druid/realtime io.druid.cli.Main server realtime
```

I would like to have something like : 

```
/usr/bin/java -server -Xmx256m -Duser.timezone=UTC -Dfile.encoding=UTF-8 -classpath /var/lib/druid/current/*:/etc/druid/historical io.druid.cli.Main server historical
```

Thanking you in advance for your feedback...

Regards,
Vincent.

**Comment by jowy** [comment]
Sorry, I haven't been receiving updates on this project for some reason. I'll review your PR. Thanks!

**Comment by jowy** [comment]
Looks good. Merged and closed.

**Comment by jowy** [comment]
Second thought, it looks like you're able to place the options in the runtime.properties file shown here: http://druid.io/docs/0.6.160/Simple-Cluster-Configuration.html and it seems to work for my cluster. Although it could possibly be runtime specific. What Java version are you using @Vincent-- ?

**Comment by Vincent--** [comment]
Hey @jowy !

Thanks for the merge.

I use this Java version :

```
vagrant@devvm:~$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

I think your setup example has combined commandline args and runtime.properties content by error on the webpage (because of html formatting, maybe...)

Before I corrected the code, druid starts correctly but java args doesn't appear in 'ps -ef'
In you cluster, do you try to modify Xmx param for instance and check the output of 'ps -ef' to see if it is really taken into account ?

**Comment by Vincent--** [comment]
Another fact to confirm my html formatting theory, on the same site, this page shows a correct config with separated commandline args and runtimes.properties :
http://druid.io/docs/0.6.160/Production-Cluster-Configuration.html
